[project]
name = "research-copilot"
version = "0.1.0"
description = "Local-First Research Co-Pilot"
authors = [{ name = "Vishwesh Bhilare" }]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["src"]

[tool.setuptools.package-dir]
"" = "."

